name: Build Electron App

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Write .env
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build TypeScript
        run: yarn build

      # Linux-specific deps (for .deb builds)
      - name: Install Linux build deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y fakeroot dpkg

      - name: Make distributables
        run: yarn make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-artifacts
          path: out/make/**
